// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as clientconfig$0 from "./clientconfig/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as network$0 from "../network/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActivateProfile 启用指定 Profile；二狗子来源必须仍存在于最新目录且当前分组可用。
 * 成功后清理原活动 Profile 的失败统计，新请求立即读取新的运行时快照。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function ActivateProfile(id) {
    return $Call.ByID(115523217, id);
}

/**
 * @param {string} accessToken
 * @returns {$CancellablePromise<void>}
 */
export function BindDoge(accessToken) {
    return $Call.ByID(819966383, accessToken);
}

/**
 * CheckClientConfig 返回某一分类当前配置文件的实时状态；它只读本地文件，不访问上游。
 * @param {string} category
 * @returns {$CancellablePromise<$models.PublicClientConfig>}
 */
export function CheckClientConfig(category) {
    return $Call.ByID(3420125402, category).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CheckForUpdate 查询官方仓库最新稳定版本。后台检查只返回状态，不下载或替换程序。
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function CheckForUpdate() {
    return $Call.ByID(3131002871).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearUsage() {
    return $Call.ByID(2120615497);
}

/**
 * CompleteOnboarding 结束首次启动引导并启用便携数据持久化；跳过和绑定成功都调用此方法。
 * @returns {$CancellablePromise<void>}
 */
export function CompleteOnboarding() {
    return $Call.ByID(3707202435);
}

/**
 * ConfigureClient 备份并写入当前分类的 CodexRelay 地址和本地访问令牌。
 * 它不改变令牌启用映射，调用方完成写入后再执行启用，避免配置失败却显示为已切换。
 * @param {string} category
 * @param {string} profileID
 * @returns {$CancellablePromise<void>}
 */
export function ConfigureClient(category, profileID) {
    return $Call.ByID(3427215176, category, profileID);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProfile(id) {
    return $Call.ByID(1954926051, id);
}

/**
 * DismissDogeNotification 一次确认当前类别窗口中的全部内容。
 * 余额和套餐都只标记当前状态；过期套餐同样保留按套餐 ID 的已确认记录，避免后续同步重复提醒。
 * 公告仍使用原有的已读状态，避免公告提醒与额度状态混用。
 * @param {string} kind
 * @returns {$CancellablePromise<void>}
 */
export function DismissDogeNotification(kind) {
    return $Call.ByID(2622079213, kind);
}

/**
 * DismissDogeTokenSwitch 在当前失败状态持续期间抑制令牌切换提示，并在失败恢复后的五分钟内继续抑制。
 * 抑制状态仅保存在内存中，不修改便携配置；失败状态恢复后会自动清理。
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function DismissDogeTokenSwitch(key) {
    return $Call.ByID(93543395, key);
}

/**
 * EditDogeToken 使用本地完整密钥创建或补全本地代理 API，但不改变当前启用映射。
 * 远端 group 不参与本地类别判断；令牌必须先完成本地类别选择。
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function EditDogeToken(id) {
    return $Call.ByID(380539881, id);
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function EnableDogeToken(id) {
    return $Call.ByID(2305030420, id);
}

/**
 * FetchProfileModels 获取当前编辑器输入对应的上游模型目录；只读上游，不修改本地配置。
 * @param {$models.ProfileInput} input
 * @returns {$CancellablePromise<$models.PublicModel[]>}
 */
export function FetchProfileModels(input) {
    return $Call.ByID(1085814066, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DesktopState>}
 */
export function GetState() {
    return $Call.ByID(3062805628).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * InstallUpdate 重新确认最新版本后下载并校验 EXE，再交给 Wails helper 原子替换并重启。
 * @returns {$CancellablePromise<void>}
 */
export function InstallUpdate() {
    return $Call.ByID(3330051357);
}

/**
 * MarkDogeAnnouncementsRead 将当前缓存中指定的公告标记为已读，并同步关闭对应公告提醒。
 * @param {number[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function MarkDogeAnnouncementsRead(ids) {
    return $Call.ByID(215903019, ids);
}

/**
 * OpenDogeProfile 使用系统默认浏览器打开二狗子用户中心，令牌生成路径由界面说明固定提示。
 * @returns {$CancellablePromise<void>}
 */
export function OpenDogeProfile() {
    return $Call.ByID(2314786001);
}

/**
 * OpenDogeTopup 使用系统默认浏览器打开二狗子购买入口。
 * 购买地址来自最近一次 `/api/user/topup/info` 同步结果，不接受前端传入的任意 URL。
 * @returns {$CancellablePromise<void>}
 */
export function OpenDogeTopup() {
    return $Call.ByID(3694618354);
}

/**
 * OpenExternalURL 使用系统默认浏览器打开前端传入的外部 HTTP(S) 地址。
 * URL 的协议和主机校验由 platform.OpenURL 统一执行，避免 WebView 在应用内处理外链，
 * 也避免把任意协议交给操作系统。
 * @param {string} raw
 * @returns {$CancellablePromise<void>}
 */
export function OpenExternalURL(raw) {
    return $Call.ByID(2419338323, raw);
}

/**
 * RedeemDoge 使用当前绑定令牌兑换额度；兑换成功后重新同步用户、套餐和购买配置。
 * 兑换码只存在于本次请求体和上游调用栈，不写入配置、日志或返回状态。
 * @param {string} code
 * @returns {$CancellablePromise<void>}
 */
export function RedeemDoge(code) {
    return $Call.ByID(1654359792, code);
}

/**
 * ReorderDogeTokens 按二狗子远端令牌 ID 保存主页顺序；名称、分组和 API 密钥只用于展示或访问，
 * 不参与令牌身份定位。
 * @param {string[]} orderKeys
 * @returns {$CancellablePromise<void>}
 */
export function ReorderDogeTokens(orderKeys) {
    return $Call.ByID(310873119, orderKeys);
}

/**
 * ReorderFailoverProfiles 保存指定类别的统一 Profile 顺序；来源不同的 Profile 可以在同一列表中相邻排列。
 * 前端只提交当前视图中的 Profile ID，后端保留未显示项并拒绝跨类别或未知 ID。
 * @param {string} category
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function ReorderFailoverProfiles(category, ids) {
    return $Call.ByID(3757833444, category, ids);
}

/**
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function ReorderProfiles(ids) {
    return $Call.ByID(107731990, ids);
}

/**
 * SaveProfile 新增或更新一个本地 Profile，并规范化其类别故障顺序。
 * 保存成功后重新评估正在进行的自动轮次，使新 Profile 可以成为目录异常后的实时候选。
 * @param {$models.ProfileInput} input
 * @returns {$CancellablePromise<void>}
 */
export function SaveProfile(input) {
    return $Call.ByID(1524050041, input);
}

/**
 * SelectDirectory 打开 Wails 原生目录选择器；取消选择返回空字符串且不报错。
 * @param {string} initialDirectory
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory(initialDirectory) {
    return $Call.ByID(1477342492, initialDirectory);
}

/**
 * SetClientConfigPath 保存外部客户端配置目录，并立即返回新的本地检测状态。
 * @param {string} category
 * @param {string} directory
 * @returns {$CancellablePromise<void>}
 */
export function SetClientConfigPath(category, directory) {
    return $Call.ByID(2510123141, category, directory);
}

/**
 * SetClientConfigSkip 保存某一外部客户端是否跳过主界面切换前的配置检查；它不改写外部文件。
 * @param {string} category
 * @param {boolean} skip
 * @returns {$CancellablePromise<void>}
 */
export function SetClientConfigSkip(category, skip) {
    return $Call.ByID(2542801733, category, skip);
}

/**
 * SetDataDirectory 迁移 config.json、usage.json 和任务通知私有队列，并让当前进程后续读写使用新目录。
 * 目标同名文件或任务通知状态不会覆盖；主配置失败会删除本次预复制的通知状态。
 * @param {string} directory
 * @returns {$CancellablePromise<void>}
 */
export function SetDataDirectory(directory) {
    return $Call.ByID(3032635246, directory);
}

/**
 * SetDogeAlertSettings 保存余额和套餐提醒的独立开关与美元阈值。
 * 关闭提醒不会删除已同步的余额、套餐或公告数据，只是不再生成对应右下角提醒。
 * @param {config$0.DogeAlertSettings} input
 * @returns {$CancellablePromise<void>}
 */
export function SetDogeAlertSettings(input) {
    return $Call.ByID(2204274041, input);
}

/**
 * @param {number} minutes
 * @returns {$CancellablePromise<void>}
 */
export function SetDogeSyncInterval(minutes) {
    return $Call.ByID(3841417432, minutes);
}

/**
 * SetDogeTokenCategories 校验整批选择后，将待导入令牌一次性创建为本地 Profile。
 * 新 Profile 按本批选择顺序追加到所属类别末尾；整批任一项无效时不保存部分结果。
 * @param {$models.DogeTokenCategoryInput[]} assignments
 * @returns {$CancellablePromise<void>}
 */
export function SetDogeTokenCategories(assignments) {
    return $Call.ByID(3990315279, assignments);
}

/**
 * @param {network$0.Settings} input
 * @returns {$CancellablePromise<void>}
 */
export function SetNetwork(input) {
    return $Call.ByID(3744998407, input);
}

/**
 * @param {config$0.Preferences} input
 * @returns {$CancellablePromise<void>}
 */
export function SetPreferences(input) {
    return $Call.ByID(3296747907, input);
}

/**
 * SetProfileAutoSwitch 设置单个 Profile 是否参加自动故障切换；手动提示模式仍可选择该 Profile。
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetProfileAutoSwitch(id, enabled) {
    return $Call.ByID(1862834343, id, enabled);
}

/**
 * SetProxyPort 校验并热切换本地代理监听端口；新端口无法绑定时不修改配置和现有监听。
 * 端口范围为 TCP 的 1-65535；成功后新请求地址立即使用新端口，已有连接由旧服务优雅退出。
 * @param {number} port
 * @returns {$CancellablePromise<void>}
 */
export function SetProxyPort(port) {
    return $Call.ByID(1746439210, port);
}

/**
 * SetTaskNotification 保存独立任务完成通知的完整访问 URL 和重试设置。
 * 修改只影响后台 watcher；它不写入 Codex 的 config.toml、hooks.json 或系统代理。
 * @param {config$0.TaskNotification} input
 * @returns {$CancellablePromise<void>}
 */
export function SetTaskNotification(input) {
    return $Call.ByID(3515011149, input);
}

/**
 * SetTokenSwitchSettings 保存所有来源共用的故障触发、阈值和候选循环策略。
 * 关闭或重新开启某个错误类型会清理其旧统计；阈值、窗口和模式变化则基于仍有效的其他统计重新评估。
 * @param {config$0.TokenSwitchSettings} input
 * @returns {$CancellablePromise<void>}
 */
export function SetTokenSwitchSettings(input) {
    return $Call.ByID(2021288413, input);
}

/**
 * SwitchDogeToken 保留旧绑定入口；实际切换已提升为所有来源共用的 Profile 切换。
 * @param {string} key
 * @param {number} tokenID
 * @returns {$CancellablePromise<void>}
 */
export function SwitchDogeToken(key, tokenID) {
    return $Call.ByID(3647092161, key, tokenID);
}

/**
 * SwitchToken 在服务端重新校验提示、类别、顺序和可用状态后启用候选 Profile。
 * 前端只提交运行时提示 key 与 Profile ID，不能借此切换到其他类别或不可用 Profile。
 * @param {string} key
 * @param {string} profileID
 * @returns {$CancellablePromise<void>}
 */
export function SwitchToken(key, profileID) {
    return $Call.ByID(3325039250, key, profileID);
}

/**
 * SyncDoge 执行用户主动触发的完整同步；已有令牌密钥也必须重新请求，只有后台定时同步使用元数据模式。
 * @returns {$CancellablePromise<void>}
 */
export function SyncDoge() {
    return $Call.ByID(1536866851);
}

/**
 * SyncDogeAnnouncements 获取公开公告和当前通知；该请求不依赖二狗子账户绑定状态。
 * @returns {$CancellablePromise<void>}
 */
export function SyncDogeAnnouncements() {
    return $Call.ByID(2451788025);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.TestResult>}
 */
export function TestProfile(id) {
    return $Call.ByID(2130459618, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * TestTaskNotification 由用户在设置页确认后测试当前 Webhook。测试请求不包含
 * rollout、任务标识、路径、prompt 或最终回复，失败不会改变 pending/outbox 队列。
 * @returns {$CancellablePromise<void>}
 */
export function TestTaskNotification() {
    return $Call.ByID(1947134911);
}

/**
 * UnbindDoge 删除绑定凭据、账户快照和全部二狗子 Profile。
 * Profile、启用映射、故障顺序及对应运行时提示在返回前一并清理，自定义 API 和公告记录不受影响。
 * @returns {$CancellablePromise<void>}
 */
export function UnbindDoge() {
    return $Call.ByID(3376309228);
}

// Private type creation functions
const $$createType0 = clientconfig$0.PublicClientConfig.createFrom;
const $$createType1 = $models.UpdateInfo.createFrom;
const $$createType2 = $models.PublicModel.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.DesktopState.createFrom;
const $$createType5 = $models.TestResult.createFrom;
