// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as clientconfig$0 from "./clientconfig/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as network$0 from "../network/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tasknotify$0 from "../tasknotify/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as usage$0 from "../usage/models.js";

export class DesktopState {
    /**
     * Creates a new DesktopState instance.
     * @param {Partial<DesktopState>} [$$source = {}] - The source object to create the DesktopState.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("updateSupported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["updateSupported"] = false;
        }
        if (!("needsOnboarding" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needsOnboarding"] = false;
        }
        if (!("dataDirectory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataDirectory"] = "";
        }
        if (!("proxyPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["proxyPort"] = 0;
        }
        if (!("listenOnAllInterfaces" in $$source)) {
            /**
             * ListenOnAllInterfaces 是网络设置页展示的监听范围，不代表当前出站网络出口。
             * @member
             * @type {boolean}
             */
            this["listenOnAllInterfaces"] = false;
        }
        if (!("clientAccessHost" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientAccessHost"] = "";
        }
        if (!("proxyUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyUrl"] = "";
        }
        if (!("proxyUrls" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["proxyUrls"] = {};
        }
        if (!("localAccessToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localAccessToken"] = "";
        }
        if (!("activeProfiles" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["activeProfiles"] = {};
        }
        if (!("profiles" in $$source)) {
            /**
             * @member
             * @type {PublicProfile[]}
             */
            this["profiles"] = [];
        }
        if (!("failoverOrder" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["failoverOrder"] = {};
        }
        if (!("clientConfigs" in $$source)) {
            /**
             * @member
             * @type {PublicClientConfig[]}
             */
            this["clientConfigs"] = [];
        }
        if (!("network" in $$source)) {
            /**
             * @member
             * @type {network$0.Settings}
             */
            this["network"] = (new network$0.Settings());
        }
        if (!("systemProxy" in $$source)) {
            /**
             * @member
             * @type {network$0.SystemProxyInfo}
             */
            this["systemProxy"] = (new network$0.SystemProxyInfo());
        }
        if (!("requests" in $$source)) {
            /**
             * @member
             * @type {usage$0.RequestRecord[]}
             */
            this["requests"] = [];
        }
        if (!("usage" in $$source)) {
            /**
             * @member
             * @type {usage$0.Overview}
             */
            this["usage"] = (new usage$0.Overview());
        }
        if (!("uptimeSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uptimeSeconds"] = 0;
        }
        if (!("preferences" in $$source)) {
            /**
             * @member
             * @type {config$0.Preferences}
             */
            this["preferences"] = (new config$0.Preferences());
        }
        if (!("tokenSwitch" in $$source)) {
            /**
             * @member
             * @type {config$0.TokenSwitchSettings}
             */
            this["tokenSwitch"] = (new config$0.TokenSwitchSettings());
        }
        if (!("taskNotification" in $$source)) {
            /**
             * @member
             * @type {TaskNotificationState}
             */
            this["taskNotification"] = (new TaskNotificationState());
        }
        if (!("doge" in $$source)) {
            /**
             * @member
             * @type {DogeState}
             */
            this["doge"] = (new DogeState());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DesktopState}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType2;
        const $$createField12_0 = $$createType4;
        const $$createField13_0 = $$createType6;
        const $$createField14_0 = $$createType7;
        const $$createField15_0 = $$createType8;
        const $$createField16_0 = $$createType10;
        const $$createField17_0 = $$createType11;
        const $$createField19_0 = $$createType12;
        const $$createField20_0 = $$createType13;
        const $$createField21_0 = $$createType14;
        const $$createField22_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("proxyUrls" in $$parsedSource) {
            $$parsedSource["proxyUrls"] = $$createField8_0($$parsedSource["proxyUrls"]);
        }
        if ("activeProfiles" in $$parsedSource) {
            $$parsedSource["activeProfiles"] = $$createField10_0($$parsedSource["activeProfiles"]);
        }
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField11_0($$parsedSource["profiles"]);
        }
        if ("failoverOrder" in $$parsedSource) {
            $$parsedSource["failoverOrder"] = $$createField12_0($$parsedSource["failoverOrder"]);
        }
        if ("clientConfigs" in $$parsedSource) {
            $$parsedSource["clientConfigs"] = $$createField13_0($$parsedSource["clientConfigs"]);
        }
        if ("network" in $$parsedSource) {
            $$parsedSource["network"] = $$createField14_0($$parsedSource["network"]);
        }
        if ("systemProxy" in $$parsedSource) {
            $$parsedSource["systemProxy"] = $$createField15_0($$parsedSource["systemProxy"]);
        }
        if ("requests" in $$parsedSource) {
            $$parsedSource["requests"] = $$createField16_0($$parsedSource["requests"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField17_0($$parsedSource["usage"]);
        }
        if ("preferences" in $$parsedSource) {
            $$parsedSource["preferences"] = $$createField19_0($$parsedSource["preferences"]);
        }
        if ("tokenSwitch" in $$parsedSource) {
            $$parsedSource["tokenSwitch"] = $$createField20_0($$parsedSource["tokenSwitch"]);
        }
        if ("taskNotification" in $$parsedSource) {
            $$parsedSource["taskNotification"] = $$createField21_0($$parsedSource["taskNotification"]);
        }
        if ("doge" in $$parsedSource) {
            $$parsedSource["doge"] = $$createField22_0($$parsedSource["doge"]);
        }
        return new DesktopState(/** @type {Partial<DesktopState>} */($$parsedSource));
    }
}

export class DogeBillingAnalysis {
    /**
     * Creates a new DogeBillingAnalysis instance.
     * @param {Partial<DogeBillingAnalysis>} [$$source = {}] - The source object to create the DogeBillingAnalysis.
     */
    constructor($$source = {}) {
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {DogeBillingSummary}
             */
            this["summary"] = (new DogeBillingSummary());
        }
        if (!("tokens" in $$source)) {
            /**
             * @member
             * @type {DogeBillingRow[]}
             */
            this["tokens"] = [];
        }
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {DogeBillingRow[]}
             */
            this["models"] = [];
        }
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {DogeBillingRow[]}
             */
            this["groups"] = [];
        }
        if (!("quota_per_unit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["quota_per_unit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DogeBillingAnalysis instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DogeBillingAnalysis}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType16;
        const $$createField1_0 = $$createType18;
        const $$createField2_0 = $$createType18;
        const $$createField3_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField0_0($$parsedSource["summary"]);
        }
        if ("tokens" in $$parsedSource) {
            $$parsedSource["tokens"] = $$createField1_0($$parsedSource["tokens"]);
        }
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField2_0($$parsedSource["models"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField3_0($$parsedSource["groups"]);
        }
        return new DogeBillingAnalysis(/** @type {Partial<DogeBillingAnalysis>} */($$parsedSource));
    }
}

export class DogeBillingOverviewItem {
    /**
     * Creates a new DogeBillingOverviewItem instance.
     * @param {Partial<DogeBillingOverviewItem>} [$$source = {}] - The source object to create the DogeBillingOverviewItem.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("quota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["quota"] = 0;
        }
        if (!("original_quota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["original_quota"] = 0;
        }
        if (!("request_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["request_count"] = 0;
        }
        if (!("token_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["token_count"] = 0;
        }
        if (!("effective_quota_per_1k_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["effective_quota_per_1k_tokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DogeBillingOverviewItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DogeBillingOverviewItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DogeBillingOverviewItem(/** @type {Partial<DogeBillingOverviewItem>} */($$parsedSource));
    }
}

export class DogeBillingRow {
    /**
     * Creates a new DogeBillingRow instance.
     * @param {Partial<DogeBillingRow>} [$$source = {}] - The source object to create the DogeBillingRow.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("total_quota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_quota"] = 0;
        }
        if (!("wallet_quota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["wallet_quota"] = 0;
        }
        if (!("subscription_quota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["subscription_quota"] = 0;
        }
        if (!("token_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["token_count"] = 0;
        }
        if (!("request_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["request_count"] = 0;
        }
        if (!("effective_quota_per_1k_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["effective_quota_per_1k_tokens"] = 0;
        }
        if (!("last_used_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_used_at"] = 0;
        }
        if (!("token_metrics" in $$source)) {
            /**
             * @member
             * @type {DogeBillingTokenMetrics}
             */
            this["token_metrics"] = (new DogeBillingTokenMetrics());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DogeBillingRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DogeBillingRow}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("token_metrics" in $$parsedSource) {
            $$parsedSource["token_metrics"] = $$createField9_0($$parsedSource["token_metrics"]);
        }
        return new DogeBillingRow(/** @type {Partial<DogeBillingRow>} */($$parsedSource));
    }
}

export class DogeBillingSummary {
    /**
     * Creates a new DogeBillingSummary instance.
     * @param {Partial<DogeBillingSummary>} [$$source = {}] - The source object to create the DogeBillingSummary.
     */
    constructor($$source = {}) {
        if (!("total_quota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_quota"] = 0;
        }
        if (!("original_total_quota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["original_total_quota"] = 0;
        }
        if (!("wallet_quota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["wallet_quota"] = 0;
        }
        if (!("wallet_multiplier_overview" in $$source)) {
            /**
             * @member
             * @type {DogeBillingOverviewItem[]}
             */
            this["wallet_multiplier_overview"] = [];
        }
        if (!("subscription_quota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["subscription_quota"] = 0;
        }
        if (!("subscription_multiplier_overview" in $$source)) {
            /**
             * @member
             * @type {DogeBillingOverviewItem[]}
             */
            this["subscription_multiplier_overview"] = [];
        }
        if (!("multiplier_overview" in $$source)) {
            /**
             * @member
             * @type {DogeBillingOverviewItem[]}
             */
            this["multiplier_overview"] = [];
        }
        if (!("token_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["token_count"] = 0;
        }
        if (!("request_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["request_count"] = 0;
        }
        if (!("effective_quota_per_1k_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["effective_quota_per_1k_tokens"] = 0;
        }
        if (!("token_metrics" in $$source)) {
            /**
             * @member
             * @type {DogeBillingTokenMetrics}
             */
            this["token_metrics"] = (new DogeBillingTokenMetrics());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DogeBillingSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DogeBillingSummary}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType21;
        const $$createField5_0 = $$createType21;
        const $$createField6_0 = $$createType21;
        const $$createField10_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("wallet_multiplier_overview" in $$parsedSource) {
            $$parsedSource["wallet_multiplier_overview"] = $$createField3_0($$parsedSource["wallet_multiplier_overview"]);
        }
        if ("subscription_multiplier_overview" in $$parsedSource) {
            $$parsedSource["subscription_multiplier_overview"] = $$createField5_0($$parsedSource["subscription_multiplier_overview"]);
        }
        if ("multiplier_overview" in $$parsedSource) {
            $$parsedSource["multiplier_overview"] = $$createField6_0($$parsedSource["multiplier_overview"]);
        }
        if ("token_metrics" in $$parsedSource) {
            $$parsedSource["token_metrics"] = $$createField10_0($$parsedSource["token_metrics"]);
        }
        return new DogeBillingSummary(/** @type {Partial<DogeBillingSummary>} */($$parsedSource));
    }
}

export class DogeBillingTokenMetrics {
    /**
     * Creates a new DogeBillingTokenMetrics instance.
     * @param {Partial<DogeBillingTokenMetrics>} [$$source = {}] - The source object to create the DogeBillingTokenMetrics.
     */
    constructor($$source = {}) {
        if (!("input_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["input_tokens"] = 0;
        }
        if (!("prompt_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["prompt_tokens"] = 0;
        }
        if (!("completion_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completion_tokens"] = 0;
        }
        if (!("cache_read_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cache_read_tokens"] = 0;
        }
        if (!("cache_write_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cache_write_tokens"] = 0;
        }
        if (!("cache_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cache_tokens"] = 0;
        }
        if (!("total_tokens_with_cache" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_tokens_with_cache"] = 0;
        }
        if (!("input_share" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["input_share"] = 0;
        }
        if (!("completion_share" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completion_share"] = 0;
        }
        if (!("avg_input_tokens_per_request" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avg_input_tokens_per_request"] = 0;
        }
        if (!("avg_completion_tokens_per_request" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avg_completion_tokens_per_request"] = 0;
        }
        if (!("avg_cache_tokens_per_request" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avg_cache_tokens_per_request"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DogeBillingTokenMetrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DogeBillingTokenMetrics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DogeBillingTokenMetrics(/** @type {Partial<DogeBillingTokenMetrics>} */($$parsedSource));
    }
}

export class DogeState {
    /**
     * Creates a new DogeState instance.
     * @param {Partial<DogeState>} [$$source = {}] - The source object to create the DogeState.
     */
    constructor($$source = {}) {
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("bound" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["bound"] = false;
        }
        if (!("account" in $$source)) {
            /**
             * @member
             * @type {PublicDogeAccount}
             */
            this["account"] = (new PublicDogeAccount());
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["user"] = {};
        }
        if (!("walletUsd" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["walletUsd"] = 0;
        }
        if (!("subscriptionsUsd" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["subscriptionsUsd"] = 0;
        }
        if (!("totalUsd" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalUsd"] = 0;
        }
        if (!("subscriptions" in $$source)) {
            /**
             * @member
             * @type {PublicDogeSubscription[]}
             */
            this["subscriptions"] = [];
        }
        if (!("redemptionEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["redemptionEnabled"] = false;
        }
        if (!("topupLink" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["topupLink"] = "";
        }
        if (!("groups" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["groups"] = [];
        }
        if (!("groupDisplayNames" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["groupDisplayNames"] = {};
        }
        if (!("tokens" in $$source)) {
            /**
             * @member
             * @type {PublicDogeToken[]}
             */
            this["tokens"] = [];
        }
        if (!("notifications" in $$source)) {
            /**
             * @member
             * @type {PublicDogeNotifications}
             */
            this["notifications"] = (new PublicDogeNotifications());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PublicDogeTokenSwitchPrompt | null | undefined}
             */
            this["tokenSwitch"] = undefined;
        }
        if (!("tokenSwitches" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: PublicDogeTokenSwitchPrompt | null }}
             */
            this["tokenSwitches"] = {};
        }
        if (!("balanceAlertEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["balanceAlertEnabled"] = false;
        }
        if (!("balanceAlertThresholdUsd" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["balanceAlertThresholdUsd"] = 0;
        }
        if (!("subscriptionAlertEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["subscriptionAlertEnabled"] = false;
        }
        if (!("subscriptionAlertThresholdUsd" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["subscriptionAlertThresholdUsd"] = 0;
        }
        if (!("syncing" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["syncing"] = false;
        }
        if (!("syncPhase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["syncPhase"] = "";
        }
        if (!("announcementSyncing" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["announcementSyncing"] = false;
        }
        if (!("syncIntervalMinutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["syncIntervalMinutes"] = 0;
        }
        if (!("lastSyncAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastSyncAt"] = "";
        }
        if (!("lastSyncError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastSyncError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DogeState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DogeState}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType22;
        const $$createField3_0 = $$createType23;
        const $$createField7_0 = $$createType25;
        const $$createField10_0 = $$createType3;
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType27;
        const $$createField13_0 = $$createType28;
        const $$createField14_0 = $$createType30;
        const $$createField15_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("account" in $$parsedSource) {
            $$parsedSource["account"] = $$createField2_0($$parsedSource["account"]);
        }
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField3_0($$parsedSource["user"]);
        }
        if ("subscriptions" in $$parsedSource) {
            $$parsedSource["subscriptions"] = $$createField7_0($$parsedSource["subscriptions"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField10_0($$parsedSource["groups"]);
        }
        if ("groupDisplayNames" in $$parsedSource) {
            $$parsedSource["groupDisplayNames"] = $$createField11_0($$parsedSource["groupDisplayNames"]);
        }
        if ("tokens" in $$parsedSource) {
            $$parsedSource["tokens"] = $$createField12_0($$parsedSource["tokens"]);
        }
        if ("notifications" in $$parsedSource) {
            $$parsedSource["notifications"] = $$createField13_0($$parsedSource["notifications"]);
        }
        if ("tokenSwitch" in $$parsedSource) {
            $$parsedSource["tokenSwitch"] = $$createField14_0($$parsedSource["tokenSwitch"]);
        }
        if ("tokenSwitches" in $$parsedSource) {
            $$parsedSource["tokenSwitches"] = $$createField15_0($$parsedSource["tokenSwitches"]);
        }
        return new DogeState(/** @type {Partial<DogeState>} */($$parsedSource));
    }
}

/**
 * DogeTokenCategoryInput 描述一个二狗子令牌的本地存放类别选择；ID 必须来自当前同步目录。
 */
export class DogeTokenCategoryInput {
    /**
     * Creates a new DogeTokenCategoryInput instance.
     * @param {Partial<DogeTokenCategoryInput>} [$$source = {}] - The source object to create the DogeTokenCategoryInput.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DogeTokenCategoryInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DogeTokenCategoryInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DogeTokenCategoryInput(/** @type {Partial<DogeTokenCategoryInput>} */($$parsedSource));
    }
}

/**
 * DogeTokenCreateInput 描述使用二狗子 User 权限令牌创建新 API 密钥所需的最小参数。
 * 分组值必须使用 /api/user/self/groups 返回的原始 key，名称由用户自行填写。
 */
export class DogeTokenCreateInput {
    /**
     * Creates a new DogeTokenCreateInput instance.
     * @param {Partial<DogeTokenCreateInput>} [$$source = {}] - The source object to create the DogeTokenCreateInput.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DogeTokenCreateInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DogeTokenCreateInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DogeTokenCreateInput(/** @type {Partial<DogeTokenCreateInput>} */($$parsedSource));
    }
}

export class DogeUsageAnalyticsQuery {
    /**
     * Creates a new DogeUsageAnalyticsQuery instance.
     * @param {Partial<DogeUsageAnalyticsQuery>} [$$source = {}] - The source object to create the DogeUsageAnalyticsQuery.
     */
    constructor($$source = {}) {
        if (!("startTimestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startTimestamp"] = 0;
        }
        if (!("endTimestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["endTimestamp"] = 0;
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }
        if (!("tokenName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tokenName"] = "";
        }
        if (!("modelName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelName"] = "";
        }
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DogeUsageAnalyticsQuery instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DogeUsageAnalyticsQuery}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DogeUsageAnalyticsQuery(/** @type {Partial<DogeUsageAnalyticsQuery>} */($$parsedSource));
    }
}

export class DogeUsageLog {
    /**
     * Creates a new DogeUsageLog instance.
     * @param {Partial<DogeUsageLog>} [$$source = {}] - The source object to create the DogeUsageLog.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["created_at"] = 0;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["type"] = 0;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("token_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token_name"] = "";
        }
        if (!("model_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model_name"] = "";
        }
        if (!("quota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["quota"] = 0;
        }
        if (!("prompt_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["prompt_tokens"] = 0;
        }
        if (!("completion_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completion_tokens"] = 0;
        }
        if (!("use_time" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["use_time"] = 0;
        }
        if (!("is_stream" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_stream"] = false;
        }
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }
        if (!("other" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["other"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DogeUsageLog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DogeUsageLog}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DogeUsageLog(/** @type {Partial<DogeUsageLog>} */($$parsedSource));
    }
}

export class DogeUsageLogPage {
    /**
     * Creates a new DogeUsageLogPage instance.
     * @param {Partial<DogeUsageLogPage>} [$$source = {}] - The source object to create the DogeUsageLogPage.
     */
    constructor($$source = {}) {
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("page_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page_size"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {DogeUsageLog[]}
             */
            this["items"] = [];
        }
        if (!("quota_per_unit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["quota_per_unit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DogeUsageLogPage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DogeUsageLogPage}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField3_0($$parsedSource["items"]);
        }
        return new DogeUsageLogPage(/** @type {Partial<DogeUsageLogPage>} */($$parsedSource));
    }
}

/**
 * ModelInput 是前端保存模型目录时提交的单条模型；ID 必须是用户确认的真实模型 ID。
 */
export class ModelInput {
    /**
     * Creates a new ModelInput instance.
     * @param {Partial<ModelInput>} [$$source = {}] - The source object to create the ModelInput.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("ownedBy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ownedBy"] = "";
        }
        if (!("contextWindow" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["contextWindow"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelInput(/** @type {Partial<ModelInput>} */($$parsedSource));
    }
}

export class ProfileInput {
    /**
     * Creates a new ProfileInput instance.
     * @param {Partial<ProfileInput>} [$$source = {}] - The source object to create the ProfileInput.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * DogeGroup 仅用于编辑已导入的二狗子令牌。空值表示不修改远端分组；
             * 真实更新必须经由当前绑定的 User 权限访问令牌完成。
             * @member
             * @type {string | undefined}
             */
            this["dogeGroup"] = undefined;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * APIKey 为空时表示编辑场景下保留已有密钥；新增 Profile 必须填写完整密钥。
             * @member
             * @type {string | undefined}
             */
            this["apiKey"] = undefined;
        }
        if (!("note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["note"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["headers"] = {};
        }
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {ModelInput[]}
             */
            this["models"] = [];
        }
        if (!("defaultModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultModel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProfileInput}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType35;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField8_0($$parsedSource["headers"]);
        }
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField9_0($$parsedSource["models"]);
        }
        return new ProfileInput(/** @type {Partial<ProfileInput>} */($$parsedSource));
    }
}

/**
 * PublicClientConfig 是高级设置和启用前检查使用的脱敏状态，不返回外部配置正文。
 * 类型别名保持 Wails 绑定中的公开字段和 JSON 形状不变。
 */
export const PublicClientConfig = clientconfig$0.PublicClientConfig;

/**
 * PublicClientConfig 是高级设置和启用前检查使用的脱敏状态，不返回外部配置正文。
 * 类型别名保持 Wails 绑定中的公开字段和 JSON 形状不变。
 * @typedef {clientconfig$0.PublicClientConfig} PublicClientConfig
 */

/**
 * PublicDogeAccount 是连接页展示的账户摘要；额度字段统一转换为美元，不包含访问令牌。
 */
export class PublicDogeAccount {
    /**
     * Creates a new PublicDogeAccount instance.
     * @param {Partial<PublicDogeAccount>} [$$source = {}] - The source object to create the PublicDogeAccount.
     */
    constructor($$source = {}) {
        if (!("userId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["userId"] = 0;
        }
        if (!("nickname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nickname"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("balanceUsd" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["balanceUsd"] = 0;
        }
        if (!("usedUsd" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["usedUsd"] = 0;
        }
        if (!("requestCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requestCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicDogeAccount instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicDogeAccount}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicDogeAccount(/** @type {Partial<PublicDogeAccount>} */($$parsedSource));
    }
}

/**
 * PublicDogeAlert 是右下角提醒窗使用的单条提醒摘要。
 */
export class PublicDogeAlert {
    /**
     * Creates a new PublicDogeAlert instance.
     * @param {Partial<PublicDogeAlert>} [$$source = {}] - The source object to create the PublicDogeAlert.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["announcementId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["amountUsd"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicDogeAlert instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicDogeAlert}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicDogeAlert(/** @type {Partial<PublicDogeAlert>} */($$parsedSource));
    }
}

/**
 * PublicDogeAnnouncement 是公告面板使用的公开公告内容，不包含访问令牌。
 */
export class PublicDogeAnnouncement {
    /**
     * Creates a new PublicDogeAnnouncement instance.
     * @param {Partial<PublicDogeAnnouncement>} [$$source = {}] - The source object to create the PublicDogeAnnouncement.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("extra" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["extra"] = "";
        }
        if (!("publishDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publishDate"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("read" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["read"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicDogeAnnouncement instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicDogeAnnouncement}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicDogeAnnouncement(/** @type {Partial<PublicDogeAnnouncement>} */($$parsedSource));
    }
}

/**
 * PublicDogeNotifications 是公告中心和提醒窗口共用的只读快照。
 */
export class PublicDogeNotifications {
    /**
     * Creates a new PublicDogeNotifications instance.
     * @param {Partial<PublicDogeNotifications>} [$$source = {}] - The source object to create the PublicDogeNotifications.
     */
    constructor($$source = {}) {
        if (!("initialized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["initialized"] = false;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("currentNotice" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentNotice"] = "";
        }
        if (!("announcements" in $$source)) {
            /**
             * @member
             * @type {PublicDogeAnnouncement[]}
             */
            this["announcements"] = [];
        }
        if (!("unreadCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unreadCount"] = 0;
        }
        if (!("alerts" in $$source)) {
            /**
             * @member
             * @type {PublicDogeAlert[]}
             */
            this["alerts"] = [];
        }
        if (!("lastSyncAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastSyncAt"] = "";
        }
        if (!("lastSyncError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastSyncError"] = "";
        }
        if (!("syncing" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["syncing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicDogeNotifications instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicDogeNotifications}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType37;
        const $$createField5_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("announcements" in $$parsedSource) {
            $$parsedSource["announcements"] = $$createField3_0($$parsedSource["announcements"]);
        }
        if ("alerts" in $$parsedSource) {
            $$parsedSource["alerts"] = $$createField5_0($$parsedSource["alerts"]);
        }
        return new PublicDogeNotifications(/** @type {Partial<PublicDogeNotifications>} */($$parsedSource));
    }
}

/**
 * PublicDogeSubscription 是提供给界面的套餐剩余摘要，金额统一转换为美元。
 */
export class PublicDogeSubscription {
    /**
     * Creates a new PublicDogeSubscription instance.
     * @param {Partial<PublicDogeSubscription>} [$$source = {}] - The source object to create the PublicDogeSubscription.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("planId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["planId"] = 0;
        }
        if (!("planTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["planTitle"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("remainingUsd" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remainingUsd"] = 0;
        }
        if (!("endTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["endTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicDogeSubscription instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicDogeSubscription}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicDogeSubscription(/** @type {Partial<PublicDogeSubscription>} */($$parsedSource));
    }
}

/**
 * PublicDogeToken 是主页令牌目录的只读摘要；Group 保留原始分组键供内部状态使用，界面只读取 GroupDisplayName。
 * Permitted 表示令牌状态、分组权限和本地完整密钥均满足切换约束，不代表已经导入 Profile。
 */
export class PublicDogeToken {
    /**
     * Creates a new PublicDogeToken instance.
     * @param {Partial<PublicDogeToken>} [$$source = {}] - The source object to create the PublicDogeToken.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("maskedKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["maskedKey"] = "";
        }
        if (!("orderKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["orderKey"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("createdTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdTime"] = 0;
        }
        if (!("accessedTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["accessedTime"] = 0;
        }
        if (!("expiredTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expiredTime"] = 0;
        }
        if (!("remainQuota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remainQuota"] = 0;
        }
        if (!("unlimitedQuota" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["unlimitedQuota"] = false;
        }
        if (!("usedQuota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["usedQuota"] = 0;
        }
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }
        if (!("groupDisplayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["groupDisplayName"] = "";
        }
        if (!("groupRatio" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["groupRatio"] = 0;
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["note"] = "";
        }
        if (!("needsCategory" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needsCategory"] = false;
        }
        if (!("permitted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["permitted"] = false;
        }
        if (!("imported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["imported"] = false;
        }
        if (!("profileId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profileId"] = "";
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicDogeToken instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicDogeToken}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicDogeToken(/** @type {Partial<PublicDogeToken>} */($$parsedSource));
    }
}

/**
 * PublicDogeTokenSwitchCandidate 是令牌切换弹窗展示的候选摘要，不包含完整密钥；Group 始终是 display_name。
 */
export class PublicDogeTokenSwitchCandidate {
    /**
     * Creates a new PublicDogeTokenSwitchCandidate instance.
     * @param {Partial<PublicDogeTokenSwitchCandidate>} [$$source = {}] - The source object to create the PublicDogeTokenSwitchCandidate.
     */
    constructor($$source = {}) {
        if (!("tokenId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tokenId"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["profileId"] = undefined;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }
        if (!("ratio" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ratio"] = 0;
        }
        if (!("selectable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["selectable"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["disabledReason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicDogeTokenSwitchCandidate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicDogeTokenSwitchCandidate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicDogeTokenSwitchCandidate(/** @type {Partial<PublicDogeTokenSwitchCandidate>} */($$parsedSource));
    }
}

/**
 * PublicDogeTokenSwitchHistory 是自动轮次中的切换或最终故障记录，不包含 API 密钥或请求正文。
 * ToName 为空表示当前令牌失败后没有可切换目标，前端应将 SwitchedAt 显示为故障时间。
 */
export class PublicDogeTokenSwitchHistory {
    /**
     * Creates a new PublicDogeTokenSwitchHistory instance.
     * @param {Partial<PublicDogeTokenSwitchHistory>} [$$source = {}] - The source object to create the PublicDogeTokenSwitchHistory.
     */
    constructor($$source = {}) {
        if (!("fromName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fromName"] = "";
        }
        if (!("toName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toName"] = "";
        }
        if (!("switchedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["switchedAt"] = "";
        }
        if (!("failureMessage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["failureMessage"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicDogeTokenSwitchHistory instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicDogeTokenSwitchHistory}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicDogeTokenSwitchHistory(/** @type {Partial<PublicDogeTokenSwitchHistory>} */($$parsedSource));
    }
}

/**
 * PublicDogeTokenSwitchPrompt 是右下角令牌切换弹窗的只读状态。
 */
export class PublicDogeTokenSwitchPrompt {
    /**
     * Creates a new PublicDogeTokenSwitchPrompt instance.
     * @param {Partial<PublicDogeTokenSwitchPrompt>} [$$source = {}] - The source object to create the PublicDogeTokenSwitchPrompt.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("failureKind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["failureKind"] = "";
        }
        if (!("failureCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failureCount"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["failureStatus"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["failureWindowMinutes"] = undefined;
        }
        if (!("currentTokenId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentTokenId"] = 0;
        }
        if (!("currentProfileId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentProfileId"] = "";
        }
        if (!("currentName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentName"] = "";
        }
        if (!("currentGroup" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentGroup"] = "";
        }
        if (!("currentRatio" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentRatio"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["switchedToName"] = undefined;
        }
        if (!("candidates" in $$source)) {
            /**
             * @member
             * @type {PublicDogeTokenSwitchCandidate[]}
             */
            this["candidates"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PublicDogeTokenSwitchHistory[] | undefined}
             */
            this["switchHistory"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["stopped"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["stoppedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["stopMessage"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicDogeTokenSwitchPrompt instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicDogeTokenSwitchPrompt}
     */
    static createFrom($$source = {}) {
        const $$createField14_0 = $$createType41;
        const $$createField15_0 = $$createType43;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("candidates" in $$parsedSource) {
            $$parsedSource["candidates"] = $$createField14_0($$parsedSource["candidates"]);
        }
        if ("switchHistory" in $$parsedSource) {
            $$parsedSource["switchHistory"] = $$createField15_0($$parsedSource["switchHistory"]);
        }
        return new PublicDogeTokenSwitchPrompt(/** @type {Partial<PublicDogeTokenSwitchPrompt>} */($$parsedSource));
    }
}

/**
 * PublicModel 是编辑页模型管理器展示的模型摘要，不包含密钥或请求正文。
 */
export class PublicModel {
    /**
     * Creates a new PublicModel instance.
     * @param {Partial<PublicModel>} [$$source = {}] - The source object to create the PublicModel.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("ownedBy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ownedBy"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["contextWindow"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicModel instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicModel}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicModel(/** @type {Partial<PublicModel>} */($$parsedSource));
    }
}

export class PublicProfile {
    /**
     * Creates a new PublicProfile instance.
     * @param {Partial<PublicProfile>} [$$source = {}] - The source object to create the PublicProfile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            /**
             * APIKey 始终为空，保留字段是为了兼容已有 Wails/前端模型；完整密钥只在
             * 后端配置中保存，不再通过状态快照下发。编辑已有 Profile 时提交空值表示
             * 保留原密钥，新增 Profile 仍必须提交完整密钥。
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("apiKeyConfigured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["apiKeyConfigured"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["apiKeyHint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["note"] = undefined;
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["headers"] = {};
        }
        if (!("models" in $$source)) {
            /**
             * @member
             * @type {PublicModel[]}
             */
            this["models"] = [];
        }
        if (!("defaultModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultModel"] = "";
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (!("previewUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["previewUrl"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["remoteTokenId"] = undefined;
        }
        if (!("skipAutoSwitch" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["skipAutoSwitch"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicProfile}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType45;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField9_0($$parsedSource["headers"]);
        }
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField10_0($$parsedSource["models"]);
        }
        return new PublicProfile(/** @type {Partial<PublicProfile>} */($$parsedSource));
    }
}

/**
 * TaskNotificationState 是消息通知设置和后台队列的公开快照。通知 URL 仅在投递时
 * 替换 {title}、{content}，状态计数和事件选择均不包含 Codex 任务、账户或令牌内容。
 */
export class TaskNotificationState {
    /**
     * Creates a new TaskNotificationState instance.
     * @param {Partial<TaskNotificationState>} [$$source = {}] - The source object to create the TaskNotificationState.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("webhookUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["webhookUrl"] = "";
        }
        if (!("events" in $$source)) {
            /**
             * @member
             * @type {config$0.TaskNotificationEvents}
             */
            this["events"] = (new config$0.TaskNotificationEvents());
        }
        if (!("idleGraceSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["idleGraceSeconds"] = 0;
        }
        if (!("requestTimeoutSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requestTimeoutSeconds"] = 0;
        }
        if (!("maxAttempts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxAttempts"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {tasknotify$0.Status}
             */
            this["status"] = (new tasknotify$0.Status());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskNotificationState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskNotificationState}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType46;
        const $$createField6_0 = $$createType47;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField2_0($$parsedSource["events"]);
        }
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField6_0($$parsedSource["status"]);
        }
        return new TaskNotificationState(/** @type {Partial<TaskNotificationState>} */($$parsedSource));
    }
}

export class TestResult {
    /**
     * Creates a new TestResult instance.
     * @param {Partial<TestResult>} [$$source = {}] - The source object to create the TestResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("reachable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["reachable"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestResult(/** @type {Partial<TestResult>} */($$parsedSource));
    }
}

export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("supported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supported"] = false;
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["latestVersion"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["publishedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["size"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = PublicProfile.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Map($Create.Any, $$createType3);
const $$createType5 = clientconfig$0.PublicClientConfig.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = network$0.Settings.createFrom;
const $$createType8 = network$0.SystemProxyInfo.createFrom;
const $$createType9 = usage$0.RequestRecord.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = usage$0.Overview.createFrom;
const $$createType12 = config$0.Preferences.createFrom;
const $$createType13 = config$0.TokenSwitchSettings.createFrom;
const $$createType14 = TaskNotificationState.createFrom;
const $$createType15 = DogeState.createFrom;
const $$createType16 = DogeBillingSummary.createFrom;
const $$createType17 = DogeBillingRow.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = DogeBillingTokenMetrics.createFrom;
const $$createType20 = DogeBillingOverviewItem.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = PublicDogeAccount.createFrom;
const $$createType23 = $Create.Map($Create.Any, $Create.Any);
const $$createType24 = PublicDogeSubscription.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = PublicDogeToken.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = PublicDogeNotifications.createFrom;
const $$createType29 = PublicDogeTokenSwitchPrompt.createFrom;
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = $Create.Map($Create.Any, $$createType30);
const $$createType32 = DogeUsageLog.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = ModelInput.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = PublicDogeAnnouncement.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = PublicDogeAlert.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = PublicDogeTokenSwitchCandidate.createFrom;
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = PublicDogeTokenSwitchHistory.createFrom;
const $$createType43 = $Create.Array($$createType42);
const $$createType44 = PublicModel.createFrom;
const $$createType45 = $Create.Array($$createType44);
const $$createType46 = config$0.TaskNotificationEvents.createFrom;
const $$createType47 = tasknotify$0.Status.createFrom;
