/*
 * @Author        : 顾青离
 * @Url           : sucaijun.com
 * @Email         : Ricky@LiHai.La
 * @Project       : CodexRelay
 * @Description   : Grok TOML 模型段和访问凭据写入
 * @File          : Grok 客户端适配器
 * @Read me       : 感谢使用 CodexRelay，源码注释齐全，支持二次开发。
 * @Remind        : 二次开发请保留原版权信息，谢谢。
 */
package clientconfig

import (
	"errors"
	"strconv"
	"strings"

	"codexrelay/internal/config"
)

func configureGrok(path, endpoint, key string, models []config.ModelEntry, defaultModel string) error {
	_, err := configureSingleResult(path, func(existing []byte) ([]byte, error) {
		return renderGrok(existing, endpoint, key, models, defaultModel)
	})
	return err
}

func renderGrok(existing []byte, endpoint, key string, models []config.ModelEntry, defaultModel string) ([]byte, error) {
	if err := validateExternalValue("代理地址", endpoint); err != nil {
		return nil, err
	}
	if err := validateExternalValue("访问令牌", key); err != nil {
		return nil, err
	}
	if len(models) == 0 {
		return nil, errors.New("Grok 配置需要至少一个模型，请先在编辑页获取模型列表")
	}
	raw := string(existing)
	if strings.TrimSpace(raw) == "" {
		raw = ""
	}
	if defaultModel == "" || !containsModel(models, defaultModel) {
		defaultModel = models[0].ID
	}
	lines := strings.Split(strings.ReplaceAll(raw, "\r\n", "\n"), "\n")
	lines = upsertTomlSectionValue(lines, "models", "default", strconv.Quote(defaultModel))
	// Remove model sections previously generated by the current adapter before
	// writing the new catalog. Only the explicit marker is managed now.
	lines = removeManagedGrokModelSections(lines)
	for _, model := range models {
		name := strings.TrimSpace(model.Name)
		if name == "" {
			name = model.ID
		}
		contextWindow := model.ContextWindow
		if contextWindow <= 0 {
			// Grok 要求正的 context_window；该默认值来自已确认的客户端适配器。
			contextWindow = 500000
		}
		header := "model." + strconv.Quote(model.ID)
		section := []string{
			"# CodexRelay managed model",
			"model = " + strconv.Quote(model.ID),
			"name = " + strconv.Quote(name),
			"base_url = " + strconv.Quote(endpoint),
			"api_key = " + strconv.Quote(key),
			"api_backend = \"responses\"",
			"context_window = " + strconv.FormatInt(contextWindow, 10),
		}
		lines = upsertTomlSection(lines, header, section)
	}
	return []byte(strings.TrimRight(strings.Join(lines, "\n"), "\n") + "\n"), nil
}

func removeManagedGrokModelSections(lines []string) []string {
	result := make([]string, 0, len(lines))
	for index := 0; index < len(lines); {
		trimmed := strings.TrimSpace(lines[index])
		if !strings.HasPrefix(trimmed, "[") || !strings.HasSuffix(trimmed, "]") {
			result = append(result, lines[index])
			index++
			continue
		}
		end := index + 1
		for end < len(lines) {
			next := strings.TrimSpace(lines[end])
			if strings.HasPrefix(next, "[") && strings.HasSuffix(next, "]") {
				break
			}
			end++
		}
		if isManagedGrokModelSection(trimmed, lines[index+1:end]) {
			if len(result) > 0 && strings.TrimSpace(result[len(result)-1]) == "# CodexRelay managed model" {
				result = result[:len(result)-1]
			}
			index = end
			continue
		}
		result = append(result, lines[index:end]...)
		index = end
	}
	return result
}

func isManagedGrokModelSection(header string, body []string) bool {
	if !strings.HasPrefix(header, "[model.") {
		return false
	}
	for _, line := range body {
		if strings.TrimSpace(line) == "# CodexRelay managed model" {
			return true
		}
	}
	return false
}
