// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * PublicClientConfig 是高级设置和启用前检查使用的脱敏状态，不返回外部配置正文。
 */
export class PublicClientConfig {
    /**
     * Creates a new PublicClientConfig instance.
     * @param {Partial<PublicClientConfig>} [$$source = {}] - The source object to create the PublicClientConfig.
     */
    constructor($$source = {}) {
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("configDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configDir"] = "";
        }
        if (!("configFile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configFile"] = "";
        }
        if (!("skipConfigReplacement" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["skipConfigReplacement"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("detected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["detected"] = false;
        }
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
		if (!("requiresProfile" in $$source)) {
			/**
			 * @member
			 * @type {boolean}
			 */
			this["requiresProfile"] = false;
		}
        if (!("statusText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusText"] = "";
        }
        if (!("lastChecked" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastChecked"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicClientConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicClientConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicClientConfig(/** @type {Partial<PublicClientConfig>} */($$parsedSource));
    }
}
