// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * No free-form config values, secrets, account identifiers or parser errors.
 */
export class CodexConfigDiagnosis {
    /**
     * Creates a new CodexConfigDiagnosis instance.
     * @param {Partial<CodexConfigDiagnosis>} [$$source = {}] - The source object to create the CodexConfigDiagnosis.
     */
    constructor($$source = {}) {
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("directory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["directory"] = "";
        }
        if (!("directorySource" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["directorySource"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("authSource" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authSource"] = "";
        }
        if (!("expectedURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expectedURL"] = "";
        }
        if (!("validTOML" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["validTOML"] = false;
        }
        if (!("uniqueProvider" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["uniqueProvider"] = false;
        }
        if (!("providerFieldsMatch" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["providerFieldsMatch"] = false;
        }
        if (!("authMatches" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["authMatches"] = false;
        }
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (!("backupCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["backupCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexConfigDiagnosis instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodexConfigDiagnosis}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodexConfigDiagnosis(/** @type {Partial<CodexConfigDiagnosis>} */($$parsedSource));
    }
}

export class CodexHistoryRepairResult {
    /**
     * Creates a new CodexHistoryRepairResult instance.
     * @param {Partial<CodexHistoryRepairResult>} [$$source = {}] - The source object to create the CodexHistoryRepairResult.
     */
    constructor($$source = {}) {
        if (!("token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token"] = "";
        }
        if (!("fileCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fileCount"] = 0;
        }
        if (!("threadCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["threadCount"] = 0;
        }
        if (!("backupID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backupID"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("targetProvider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetProvider"] = "";
        }
        if (!("skippedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["skippedCount"] = 0;
        }
        if (!("warning" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["warning"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodexHistoryRepairResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CodexHistoryRepairResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodexHistoryRepairResult(/** @type {Partial<CodexHistoryRepairResult>} */($$parsedSource));
    }
}

/**
 * PublicClientConfig 是高级设置和启用前检查使用的脱敏状态，不返回外部配置正文。
 */
export class PublicClientConfig {
    /**
     * Creates a new PublicClientConfig instance.
     * @param {Partial<PublicClientConfig>} [$$source = {}] - The source object to create the PublicClientConfig.
     */
    constructor($$source = {}) {
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("configDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configDir"] = "";
        }
        if (!("configDirSource" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configDirSource"] = "";
        }
        if (!("configFile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configFile"] = "";
        }
        if (!("skipConfigReplacement" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["skipConfigReplacement"] = false;
        }
        if (!("officialBackupAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["officialBackupAvailable"] = false;
        }
        if (!("configState" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configState"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("detected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["detected"] = false;
        }
        if (!("configured" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["configured"] = false;
        }
        if (!("requiresProfile" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["requiresProfile"] = false;
        }
        if (!("statusText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusText"] = "";
        }
        if (!("lastChecked" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastChecked"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicClientConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicClientConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicClientConfig(/** @type {Partial<PublicClientConfig>} */($$parsedSource));
    }
}
